In [46]:
import pandas as pd
a=pd.read_csv('/content/train.csv')
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [47]:
X=a.drop(columns=['price_range'])
Y=a[['price_range']]
print(X)
print(Y)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0

In [48]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range = (0,1))
X_norm=scaler.fit_transform(X)
print(X_norm)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [49]:
from sklearn.model_selection import train_test_split
X_train,Y_train,X_test,Y_test=train_test_split(X,Y,test_size=0.30)
print(X_train.shape)
print("Training Data:",X_train)
print(Y_train.shape)
print(Y_train)
print(X_test.shape)
print("Testing Data:",X_test)
print(Y_test.shape)
print(Y_test)

(1400, 20)
Training Data:       battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
135            1213     1          0.5         0   0       0          16   
315            1126     0          0.7         0   3       0          49   
1192           1030     1          0.5         0   4       1          37   
666             890     1          2.2         1   4       0          44   
1477           1150     1          2.7         0   0       0          39   
...             ...   ...          ...       ...  ..     ...         ...   
1238           1597     1          0.9         0   4       1           4   
178             947     0          0.8         1   0       1          22   
573            1900     1          0.5         1   0       1          55   
1299            871     0          0.6         0   2       0          52   
749             802     1          2.4         1   1       0          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ra

In [50]:
import pandas as pd
data=pd.read_csv('/content/heart.csv')
print(data)


     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [51]:
'''X1=a.drop(columns=['target'])
Y1=a[['target']]
print(X1)
print(Y1)'''


Y=data.drop(columns=["target"],axis=1)
Y=data["target"]
print(X)


      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0

In [52]:
print(Y)

'''from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range = (0,1))
X1_norm=scaler.fit_transform(X1)
print(X1_norm)'''


0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


'from sklearn.preprocessing import MinMaxScaler\nscaler = MinMaxScaler(feature_range = (0,1))\nX1_norm=scaler.fit_transform(X1)\nprint(X1_norm)'

In [53]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
X=scaler.fit_transform(X)

In [54]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3)
print(x)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [55]:
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[0.6875     0.         0.         ... 0.5        0.75       0.66666667]
 [0.64583333 0.         1.         ... 1.         0.         0.66666667]
 [0.5625     1.         0.         ... 0.5        0.25       0.66666667]
 ...
 [0.75       0.         0.66666667 ... 1.         0.25       0.66666667]
 [0.25       1.         0.33333333 ... 1.         0.         0.66666667]
 [0.625      1.         0.         ... 0.5        0.5        0.33333333]]
[[0.72916667 1.         0.         ... 0.         0.25       0.66666667]
 [0.625      1.         0.33333333 ... 1.         0.         0.66666667]
 [0.79166667 0.         0.         ... 1.         0.5        0.66666667]
 ...
 [0.77083333 0.         0.         ... 0.5        0.5        1.        ]
 [0.27083333 1.         0.         ... 1.         0.         0.66666667]
 [0.52083333 1.         0.33333333 ... 1.         0.         1.        ]]
252    0
147    1
214    0
55     1
59     1
      ..
149    1
251    0
28     1
133    1
297    0
Name: target,

In [56]:
import numpy as np

X1=X_train[0]
X2=X_train[1]
X3=X_train[2]
X4=X_train[3]
X5=X_train[4]
X6=X_train[5]
X7=X_train[6]
X8=X_train[7]
X9=X_train[8]
X10=X_train[9]
X11=X_train[10]
X12=X_train[11]
X13=X_train[12]
Y_p=[]
def perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(X1)):
    z=X1[i]*w1+X2[i]*w2+X3[i]*w3+X4[i]*w4+X5[i]*w5+X6[i]*w6+X7[i]*w7+X8[i]*w8+X9[i]*w9+X10[i]*w10+X11[i]*w11+X12[i]*w12+X13[i]*w13+b
    s=1/1+np.exp(-z)
    if (s>=0.5):
      Y_p.append(1)
    else:
      Y_p.append(0)
  return Y_p

print(perceptron(1,2,3,1,2,3,1,2,3,1,2,3,1,10))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
