In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
from sklearn.decomposition import PCA
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
df_train = pd.read_csv("/content/drive/MyDrive/train-1.csv")
df_test = pd.read_csv("/content/drive/MyDrive/test.csv")

In [ ]:
df_train.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000001                      188          1          0   
1  F00000003                      209          1          0   
2  F00000004                      257          1          0   
3  F00000005                      257          1          1   
4  F00000006                      342          1          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                0.0   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   

   Number_Weeks_Quit  Season  Crop_Damage  
0                  0       1            0  
1                  0       2            1  
2                  0       2            1  
3                  0       2            1  
4                  0       2            1

In [ ]:
df_test.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000002                      188          1          1   
1  F00000007                      410          1          1   
2  F00000011                      626          1          0   
3  F00000013                      731          1          0   
4  F00000014                      789          0          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                NaN   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   

   Number_Weeks_Quit  Season  
0                  0       2  
1                  0       2  
2                  0       2  
3                  0       2  
4                  0       1

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88858 entries, 0 to 88857
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       88858 non-null  object 
 1   Estimated_Insects_Count  88858 non-null  int64  
 2   Crop_Type                88858 non-null  int64  
 3   Soil_Type                88858 non-null  int64  
 4   Pesticide_Use_Category   88858 non-null  int64  
 5   Number_Doses_Week        88858 non-null  int64  
 6   Number_Weeks_Used        79858 non-null  float64
 7   Number_Weeks_Quit        88858 non-null  int64  
 8   Season                   88858 non-null  int64  
 9   Crop_Damage              88858 non-null  int64  
dtypes: float64(1), int64(8), object(1)
memory usage: 6.8+ MB


In [ ]:
df_train.drop(columns=['ID'],axis=1)

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                          188          1          0                       1   
1                          209          1          0                       1   
2                          257          1          0                       1   
3                          257          1          1                       1   
4                          342          1          0                       1   
...                        ...        ...        ...                     ...   
88853                     3337          1          0                       2   
88854                     3516          1          0                       2   
88855                     3516          1          0                       2   
88856                     3702          1          0                       2   
88857                     3895          1          0                       2   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                      0                0.0                  0       1   
1                      0                0.0                  0       2   
2                      0                0.0                  0       2   
3                      0                0.0                  0       2   
4                      0                0.0                  0       2   
...                  ...                ...                ...     ...   
88853                 10               12.0                 44       3   
88854                 10               20.0                 38       1   
88855                 15               40.0                  8       2   
88856                 10               25.0                 18       3   
88857                 20               37.0                  7       3   

       Crop_Damage  
0                0  
1                1  
2                1  
3                1  
4                1  
...            ...  
88853            0  
88854            0  
88855            0  
88856            0  
88857            0  

[88858 rows x 9 columns]

In [ ]:
df_test.drop(columns=['ID'],axis=1)

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                          188          1          1                       1   
1                          410          1          1                       1   
2                          626          1          0                       1   
3                          731          1          0                       1   
4                          789          0          0                       1   
...                        ...        ...        ...                     ...   
59305                     3337          1          0                       2   
59306                     3516          1          0                       2   
59307                     3702          1          0                       2   
59308                     3702          1          0                       2   
59309                     3895          1          0                       2   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  
0                      0                NaN                  0       2  
1                      0                0.0                  0       2  
2                      0                0.0                  0       2  
3                      0                0.0                  0       2  
4                      0                0.0                  0       1  
...                  ...                ...                ...     ...  
59305                 20               34.0                 12       1  
59306                 20               32.0                 10       2  
59307                 10                NaN                 48       1  
59308                 10               28.0                 17       2  
59309                  5               52.0                  7       1  

[59310 rows x 8 columns]

In [ ]:
df_train.dropna(inplace = True)

In [ ]:
df_test.dropna(inplace = True)

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53417 entries, 1 to 59309
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       53417 non-null  object 
 1   Estimated_Insects_Count  53417 non-null  int64  
 2   Crop_Type                53417 non-null  int64  
 3   Soil_Type                53417 non-null  int64  
 4   Pesticide_Use_Category   53417 non-null  int64  
 5   Number_Doses_Week        53417 non-null  int64  
 6   Number_Weeks_Used        53417 non-null  float64
 7   Number_Weeks_Quit        53417 non-null  int64  
 8   Season                   53417 non-null  int64  
dtypes: float64(1), int64(7), object(1)
memory usage: 4.1+ MB


In [ ]:
x=df_train.drop(columns=['Crop_Damage','ID'],axis=1)
y=df_train['Crop_Damage']

In [ ]:
from imblearn.over_sampling import SMOTE    #using SMOTE Method
smt=SMOTE()
x,y=smt.fit_resample(x,y)


In [ ]:
from sklearn.model_selection import train_test_split

# Assuming train_data is your complete dataset
# Split the data into training and testing sets (80% train, 20% test)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25,random_state = 42)


# Print the shapes of the resulting sets
print("Training set shape:", x_train.shape, y_train.shape)
print("Testing set shape:", x_test.shape, y_test.shape)

Training set shape: (150171, 8) (150171,)
Testing set shape: (50058, 8) (50058,)


In [ ]:
from sklearn.decomposition import PCA



# Initialize PCA for the desired number of components (let's say 10 components)
num_components = 5
pca = PCA(n_components=num_components)

# Fit and transform PCA on the training data
x_train_pca = pca.fit_transform(x_train)

# Transform testing and validation data based on the PCA from the training set
x_test_pca = pca.transform(x_test)

# Check the shape of transformed datasets
print("Transformed Training set shape:", x_train_pca.shape)
print("Transformed Testing set shape:", x_test_pca.shape)


Transformed Training set shape: (150171, 5)
Transformed Testing set shape: (50058, 5)


In [ ]:
x_test = df_test.drop(columns=['ID'],axis = 1) # Features in the testing set
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train_pca, y_train)
y_pred = knn.predict(x_test_pca)
print(y_pred)

[2 2 1 ... 2 0 1]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train_pca, y_train)
y_pred = knn.predict(x_test_pca)
print(y_pred)
accuracy_KNN = accuracy_score(y_test, y_pred)
print("Accuracy is :",accuracy_KNN)
print(classification_report(y_test, y_pred))

[2 2 1 ... 2 0 1]
Accuracy is : 0.7760198170122657
              precision    recall  f1-score   support

           0       0.79      0.69      0.74     16503
           1       0.72      0.78      0.75     16761
           2       0.82      0.86      0.84     16794

    accuracy                           0.78     50058
   macro avg       0.78      0.78      0.77     50058
weighted avg       0.78      0.78      0.77     50058



In [ ]:
# make prediction on testing dataset
from sklearn.ensemble import HistGradientBoostingClassifier


x_test = df_test.drop(columns=['ID'],axis = 1) # Features in the testing set

# Train the model
model = HistGradientBoostingClassifier()
model.fit(x_train_pca, y_train)

# Make predictions on the testing dataset
predictions = model.predict(x_test_pca)
print(predictions)

[2 1 2 ... 2 0 2]


In [ ]:
from sklearn.ensemble import HistGradientBoostingClassifier


  # Features in the testing set

# Train the model
model = HistGradientBoostingClassifier()
model.fit(x_train_pca, y_train)

# Make predictions on the testing dataset
predictions = model.predict(x_test_pca)
print(predictions)
accuracy_boost = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy_boost)
print(classification_report(y_test, predictions))

[2 1 2 ... 2 0 1]
Accuracy: 0.6699428662751209
              precision    recall  f1-score   support

           0       0.71      0.73      0.72     16503
           1       0.64      0.48      0.55     16761
           2       0.65      0.80      0.72     16794

    accuracy                           0.67     50058
   macro avg       0.67      0.67      0.66     50058
weighted avg       0.67      0.67      0.66     50058

